AllCops:
  Exclude:
    - "db/schema.rb"

Style/ClassAndModuleChildren:
  Enabled: False

Metrics/BlockLength:
  Exclude:
    - "spec/models/*.rb"
    - "spec/app/*.rb"

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
