default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE_DEV', 'shorty_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE_TEST', 'shorty_test') %>

production:
  <<: *default
  password: <%= ENV.fetch('POSTGRES_DATABASE', 'shorty') %>
