development:
  clients:
    default:
      database: urlshortener
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: urlshortener-test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
